../dut/Cos/Cos.v
../dut/Cos/CLZ32.v
../dut/Cos/CORDIC.v
../dut/Cos/divider_BW48_v3.v
../dut/Cos/FixedToFloat32.v
../dut/Cos/FloatToFixed32.v
../dut/Cos/FP_divider_bw32.v
../dut/Cos/FP_extract.v
../dut/Cos/FP_multiplier_bw32.v
../dut/Cos/full_adder.v
../dut/Cos/full_subtractor.v
../dut/Cos/leadingOneDetector.v
../dut/Cos/multiplier.v
../dut/Cos/TrigRangeReducer.v
../dut/Cos/twoscomplement.v
../tb/tb_func.sv
../tb/tb_Cos.sv
