../dut/Sin/Sin.v
../dut/Sin/CLZ32.v
../dut/Sin/CORDIC.v
../dut/Sin/divider_BW48_v3.v
../dut/Sin/FixedToFloat32.v
../dut/Sin/FloatToFixed32.v
../dut/Sin/FP_divider_bw32.v
../dut/Sin/FP_extract.v
../dut/Sin/FP_multiplier_bw32.v
../dut/Sin/full_adder.v
../dut/Sin/full_subtractor.v
../dut/Sin/leadingOneDetector.v
../dut/Sin/multiplier.v
../dut/Sin/TrigRangeReducer.v
../dut/Sin/twoscomplement.v
../tb/tb_func.sv
../tb/tb_sin.sv
