#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog -f ../filelist/filelist_Cos.f  
#vlog -f ../filelist/filelist_13cc.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Being to Run Simulation             "
echo "+====================================="
vsim work.tb_Cos -t 1ns

################## #################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/clock
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/reset
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/io_in
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/io_out

run 5us                                                                            
