#!/bin/csh -f
################################################################################
# simulation top script
# change modelsim in this file dir and run "do this_file.do"
# project dir ---+---> hdl source dir
#                +---> sim script dir
#
################################################################################

# check if current dir has modelsim config file
set has_config  [file exists modelsim.do]
# config modelsim 
if {$has_config==1} { do modelsim.do  ; }

echo "+====================================="
echo "| Creat Lib Work soc                  "
echo "+====================================="
vlib work
vmap work work 

echo "+====================================="
echo "| Complile RTL Code of soc            "
echo "+====================================="
vlog +define+COS_N32_PD1_BW32\
     -f ../filelist/filelist_cos_n32_pd1_bw32.f  
#vlog -f ../filelist/filelist_13cc.f  

echo "+====================================="
echo "| Compiler Pass                       "
echo "| Begin to Run Simulation             "
echo "+====================================="
vsim work.tb_Cos -t 1ns

################## #################### mus  ####################################
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/clock
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/reset
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/io_in
add wave -noupdate -format logic -radix hexadecimal tb_Cos/u_Cos/io_out

add wave -position insertpoint /tb_Cos/u_Cos/reducer/clock
add wave -position insertpoint /tb_Cos/u_Cos/reducer/reset
add wave -position insertpoint /tb_Cos/u_Cos/reducer/io_in
add wave -position insertpoint /tb_Cos/u_Cos/reducer/io_out
add wave -position insertpoint /tb_Cos/u_Cos/tofixedz0/io_in
add wave -position insertpoint /tb_Cos/u_Cos/tofixedz0/io_out

add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofixedx0/io_in
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofixedx0/io_out
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofixedy0/io_in
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofixedy0/io_out
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofloatxout/io_in
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofloatxout/io_out
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofloatyout/io_in
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofloatyout/io_out
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofloatzout/io_in
add wave -position insertpoint /tb_Cos/u_Cos/cordic/tofloatzout/io_out

add wave -position insertpoint /tb_Cos/u_Cos/reducer/divider/io_in_a
add wave -position insertpoint /tb_Cos/u_Cos/reducer/divider/io_out_s
add wave -position insertpoint /tb_Cos/u_Cos/reducer/extractor/io_in_a
add wave -position insertpoint /tb_Cos/u_Cos/reducer/extractor/io_out_frac
add wave -position insertpoint /tb_Cos/u_Cos/reducer/mul/io_in_a
add wave -position insertpoint /tb_Cos/u_Cos/reducer/mul/io_out_s

run 1us                                                                            
